[[language]]
name = "python"
scope = "source.python"
injection-regex = "python"
file-types = ["py"]
shebangs = ["python"]
roots = []
comment-token = "#"
# TODO: pyls needs utf-8 offsets
# config = { pylsp.plugins.flake8.config = ".flake8",  pylsp.plugins.flake8.enabled = true}
indent = { tab-width = 4, unit = "    " }
